[workspace]
members = [
  "humphrey",
  "humphrey-auth",
  "humphrey-json",
  "humphrey-json-derive",
  "humphrey-server",
  "humphrey-ws"
]
resolver = "2"

[patch.crates-io]
humphrey = { path = "./humphrey" }