[package]
name = "auth"
version = "0.1.0"
edition = "2021"

[dependencies]
humphrey = "^0.6.0"
humphrey_auth = { version = "^0.1.4", features = ["humphrey", "json"] }
humphrey_json = "^0.1.1"
jasondb = "^0.2.2"

[workspace]