[package]
name = "async_websocket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humphrey_ws = { path = "../../humphrey-ws" }

[workspace]