on: [push, pull_request]

name: JSON Specification Compliance

jobs:
  test:
    name: Test Specification Compliance
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -p humphrey_json spec -- --ignored
